TOKEN-TYPE          TOKEN-VALUE
-------------------------------------------------
PROGRAM             program
NAME                hello
SEMI                ;
CONST               const
NAME                cn
EQUAL               =
INTEGER             2
SEMI                ;
NAME                dn
EQUAL               =
FLOAT_NUM           123.23
SEMI                ;
TYPE                type
NAME                ar
EQUAL               =
RECORD              record
NAME                a
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                b
COLON               :
SYS_TYPE            integer
SEMI                ;
END                 end
SEMI                ;
VAR                 var
NAME                i
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                j
COLON               :
NAME                ar
SEMI                ;
NAME                str
COLON               :
NAME                string
SEMI                ;
FUNCTION            function
NAME                add
LP                  (
NAME                a
COMMA               ,
NAME                b
COLON               :
SYS_TYPE            integer
RP                  )
COLON               :
SYS_TYPE            integer
SEMI                ;
BEGIN_TOKEN         begin
NAME                add
ASSIGN              :=
NAME                a
PLUS                +
NAME                b
SEMI                ;
END                 end
SEMI                ;
BEGIN_TOKEN         begin
NAME                j
DOT                 .
NAME                a
ASSIGN              :=
INTEGER             0
SEMI                ;
FOR                 for
NAME                i
ASSIGN              :=
INTEGER             0
TO                  to
INTEGER             10
DO                  do
BEGIN_TOKEN         begin
NAME                j
DOT                 .
NAME                a
ASSIGN              :=
NAME                j
DOT                 .
NAME                a
PLUS                +
NAME                i
SEMI                ;
END                 end
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                j
DOT                 .
NAME                a
RP                  )
SEMI                ;
WHILE               while
NAME                i
GT                  >
INTEGER             5
DO                  do
BEGIN_TOKEN         begin
NAME                j
DOT                 .
NAME                a
ASSIGN              :=
NAME                add
LP                  (
NAME                j
DOT                 .
NAME                a
COMMA               ,
NAME                j
DOT                 .
NAME                a
RP                  )
SEMI                ;
NAME                i
ASSIGN              :=
NAME                i
MINUS               -
INTEGER             1
SEMI                ;
END                 end
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                j
DOT                 .
NAME                a
RP                  )
SEMI                ;
REPEAT              repeat
NAME                j
DOT                 .
NAME                a
ASSIGN              :=
NAME                j
DOT                 .
NAME                a
DIV                 /
INTEGER             2
SEMI                ;
UNTIL               until
NAME                j
DOT                 .
NAME                a
LT                  <
INTEGER             100
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                j
DOT                 .
NAME                a
RP                  )
SEMI                ;
CASE                case
NAME                j
DOT                 .
NAME                a
%INTEGER             4
OF                  of
INTEGER             0
COLON               :
NAME                str
ASSIGN              :=
'NAME                A1
'SEMI                ;
INTEGER             1
COLON               :
NAME                str
ASSIGN              :=
'NAME                B2
'SEMI                ;
NAME                cn
COLON               :
NAME                str
ASSIGN              :=
'NAME                C3
'SEMI                ;
INTEGER             3
COLON               :
NAME                str
ASSIGN              :=
'NAME                D4
'SEMI                ;
END                 end
SEMI                ;
IF                  if
NAME                j
DOT                 .
NAME                a
GE                  >=
INTEGER             0
THEN                then
BEGIN_TOKEN         begin
NAME                j
DOT                 .
NAME                a
ASSIGN              :=
NAME                j
DOT                 .
NAME                a
PLUS                +
INTEGER             1
SEMI                ;
END                 end
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                j
DOT                 .
NAME                a
RP                  )
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                str
RP                  )
SEMI                ;
END                 end
DOT                 .
