TOKEN-TYPE          TOKEN-VALUE
-------------------------------------------------
PROGRAM             program
NAME                hello
SEMI                ;
VAR                 var
NAME                c
COLON               :
ARRAY               array
LB                  [
INTEGER             0
DOTDOT              ..
INTEGER             10
RB                  ]
OF                  of
SYS_TYPE            integer
SEMI                ;
NAME                d
COLON               :
ARRAY               array
LB                  [
INTEGER             0
DOTDOT              ..
INTEGER             10
RB                  ]
OF                  of
SYS_TYPE            integer
SEMI                ;
NAME                i
COLON               :
SYS_TYPE            integer
SEMI                ;
BEGIN_TOKEN         begin
FOR                 for
NAME                i
ASSIGN              :=
INTEGER             0
TO                  to
INTEGER             10
DO                  do
BEGIN_TOKEN         begin
NAME                c
LB                  [
NAME                i
RB                  ]
ASSIGN              :=
NAME                i
SEMI                ;
NAME                d
LB                  [
NAME                i
RB                  ]
ASSIGN              :=
INTEGER             10
MINUS               -
NAME                i
SEMI                ;
END                 end
SEMI                ;
FOR                 for
NAME                i
ASSIGN              :=
INTEGER             0
TO                  to
INTEGER             10
DO                  do
BEGIN_TOKEN         begin
NAME                c
LB                  [
NAME                i
RB                  ]
ASSIGN              :=
NAME                c
LB                  [
NAME                i
RB                  ]
MUL                 *
NAME                d
LB                  [
NAME                i
RB                  ]
SEMI                ;
END                 end
SEMI                ;
FOR                 for
NAME                i
ASSIGN              :=
INTEGER             0
TO                  to
INTEGER             10
DO                  do
BEGIN_TOKEN         begin
SYS_PROC            writeln
LP                  (
NAME                c
LB                  [
NAME                i
RB                  ]
RP                  )
SEMI                ;
IF                  if
NAME                c
LB                  [
NAME                i
RB                  ]
EQUAL               =
INTEGER             2
THEN                then
BEGIN_TOKEN         begin
NAME                c
LB                  [
NAME                i
RB                  ]
ASSIGN              :=
INTEGER             1
SEMI                ;
END                 end
SEMI                ;
END                 end
SEMI                ;
FOR                 for
NAME                i
ASSIGN              :=
INTEGER             0
TO                  to
INTEGER             10
DO                  do
BEGIN_TOKEN         begin
SYS_PROC            writeln
LP                  (
NAME                c
LB                  [
NAME                i
RB                  ]
RP                  )
SEMI                ;
END                 end
SEMI                ;
END                 end
DOT                 .
