TOKEN-TYPE          TOKEN-VALUE
-------------------------------------------------
PROGRAM             program
NAME                hello
SEMI                ;
CONST               const
NAME                cn
EQUAL               =
INTEGER             2
SEMI                ;
NAME                dn
EQUAL               =
FLOAT_NUM           123.23
SEMI                ;
VAR                 var
NAME                k
COLON               :
SYS_TYPE            integer
SEMI                ;
PROCEDURE           procedure
NAME                outer
SEMI                ;
VAR                 var
NAME                res
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                added
COLON               :
SYS_TYPE            integer
SEMI                ;
FUNCTION            function
NAME                inner1
LP                  (
NAME                a
COMMA               ,
NAME                b
COLON               :
SYS_TYPE            integer
RP                  )
COLON               :
SYS_TYPE            integer
SEMI                ;
BEGIN_TOKEN         begin
NAME                inner1
ASSIGN              :=
NAME                a
PLUS                +
NAME                b
SEMI                ;
END                 end
SEMI                ;
PROCEDURE           procedure
NAME                inner2
LP                  (
VAR                 var
NAME                aa
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                b
COLON               :
SYS_TYPE            integer
RP                  )
SEMI                ;
BEGIN_TOKEN         begin
NAME                aa
ASSIGN              :=
NAME                inner1
LP                  (
NAME                aa
COMMA               ,
NAME                b
RP                  )
SEMI                ;
NAME                k
ASSIGN              :=
NAME                k
PLUS                +
INTEGER             10
SEMI                ;
END                 end
SEMI                ;
BEGIN_TOKEN         begin
NAME                k
ASSIGN              :=
INTEGER             0
SEMI                ;
NAME                inner2
LP                  (
NAME                k
COMMA               ,
INTEGER             10
RP                  )
SEMI                ;
END                 end
SEMI                ;
BEGIN_TOKEN         begin
NAME                outer
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                k
RP                  )
SEMI                ;
END                 end
DOT                 .
