TOKEN-TYPE          TOKEN-VALUE
-------------------------------------------------
PROGRAM             program
NAME                hello
SEMI                ;
VAR                 var
NAME                ans
COLON               :
SYS_TYPE            integer
SEMI                ;
FUNCTION            function
NAME                gcd
LP                  (
NAME                a
COMMA               ,
NAME                b
COLON               :
SYS_TYPE            integer
RP                  )
COLON               :
SYS_TYPE            integer
SEMI                ;
BEGIN_TOKEN         begin
IF                  if
NAME                b
EQUAL               =
INTEGER             0
THEN                then
BEGIN_TOKEN         begin
NAME                gcd
ASSIGN              :=
NAME                a
SEMI                ;
END                 end
ELSE                else
BEGIN_TOKEN         begin
NAME                gcd
ASSIGN              :=
NAME                gcd
LP                  (
NAME                b
COMMA               ,
NAME                a
%NAME                b
RP                  )
SEMI                ;
END                 end
SEMI                ;
END                 end
SEMI                ;
BEGIN_TOKEN         begin
NAME                ans
ASSIGN              :=
NAME                gcd
LP                  (
INTEGER             9
COMMA               ,
INTEGER             36
RP                  )
MUL                 *
NAME                gcd
LP                  (
INTEGER             3
COMMA               ,
INTEGER             6
RP                  )
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                ans
RP                  )
SEMI                ;
END                 end
DOT                 .
