TOKEN-TYPE          TOKEN-VALUE
-------------------------------------------------
PROGRAM             program
NAME                hello
SEMI                ;
VAR                 var
NAME                f
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                k
COLON               :
SYS_TYPE            integer
SEMI                ;
FUNCTION            function
NAME                go
LP                  (
VAR                 var
NAME                b
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                a
COLON               :
SYS_TYPE            integer
RP                  )
COLON               :
SYS_TYPE            integer
SEMI                ;
VAR                 var
NAME                fk
COLON               :
SYS_TYPE            integer
SEMI                ;
NAME                t
COLON               :
SYS_TYPE            real
SEMI                ;
BEGIN_TOKEN         begin
IF                  if
NAME                a
GT                  >
INTEGER             0
THEN                then
BEGIN_TOKEN         begin
NAME                go
ASSIGN              :=
NAME                a
MUL                 *
NAME                go
LP                  (
NAME                b
COMMA               ,
NAME                a
MINUS               -
INTEGER             1
RP                  )
SEMI                ;
END                 end
ELSE                else
BEGIN_TOKEN         begin
NAME                go
ASSIGN              :=
INTEGER             1
SEMI                ;
END                 end
SEMI                ;
NAME                b
ASSIGN              :=
NAME                b
PLUS                +
NAME                go
SEMI                ;
NAME                k
ASSIGN              :=
NAME                k
PLUS                +
NAME                go
SEMI                ;
END                 end
SEMI                ;
BEGIN_TOKEN         begin
NAME                k
ASSIGN              :=
INTEGER             0
SEMI                ;
NAME                f
ASSIGN              :=
NAME                go
LP                  (
NAME                k
COMMA               ,
INTEGER             5
RP                  )
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                f
RP                  )
SEMI                ;
SYS_PROC            writeln
LP                  (
NAME                k
RP                  )
SEMI                ;
END                 end
DOT                 .
